version: '3'
services:
  api:
    container_name: api
    hostname: "0.0.0.0"
    build:
      dockerfile: ./.docker/api/Dockerfile
    volumes:
      - ./api/:/api/

  frontend:
    container_name: frontend
    build:
      dockerfile: ./.docker/frontend/Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - ./frontend/:/frontend/

  web-server:
    container_name: web-server
    hostname: "0.0.0.0"
    build:
      dockerfile: ./.docker/nginx/Dockerfile
    ports:
      - '8000:80'
    volumes:
      - ./.docker/nginx/logs/:/api/logs/
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./api/resources/files:/api/resources/files/

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: chat
    restart: always
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  echo:
    build:
      dockerfile: ./.docker/echo/Dockerfile
    container_name: echo
    volumes:
      - ./echo:/echo
    ports:
      - "6002:6001"

  redis:
    container_name: redis
    image: redis
    restart: always
    volumes:
      - ./.docker/redis/data:/data
    ports:
      - '6379:6379'

